# Generated by Django 5.2.4 on 2025-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainScanUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
